package com.his.scs.view;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;

import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.LayoutStyle.ComponentPlacement;

import com.his.scs.helper.AppConstants;
import java.awt.Font;

public class ConfigPatientManualView extends javax.swing.JFrame {

	private BSLLiveGraph graph;

	/**
	 * Creates new form ConfigPatientManualView
	 */
	public ConfigPatientManualView() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">                          
	private void initComponents() {
		this.setTitle("Insulin / Glucagon Pump");
		jTextField2 = new javax.swing.JTextField();
		jButton2 = new javax.swing.JButton();
		jPanel1 = new javax.swing.JPanel();
		jLabel2 = new javax.swing.JLabel();
		chckbxManualMode = new javax.swing.JCheckBox();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		insulinDosageField = new javax.swing.JTextField();
		glucagonDosageField = new javax.swing.JTextField();
		jLabel8 = new javax.swing.JLabel();
		jLabel10 = new javax.swing.JLabel();
		saveButton = new javax.swing.JButton();
		saveButton.setFont(new Font("Tahoma", Font.BOLD, 11));
		jButton3 = new javax.swing.JButton();

		jTextField2.setColumns(3);

		jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		jButton2.setText("Back");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);

		jPanel1.setBorder(null);

		jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
		jLabel2.setText("DOCTOR MODE");

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1Layout.setHorizontalGroup(
				jPanel1Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
						.addGap(145)
						.addComponent(jLabel2)
						.addContainerGap(148, Short.MAX_VALUE))
				);
		jPanel1Layout.setVerticalGroup(
				jPanel1Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
						.addContainerGap()
						.addComponent(jLabel2)
						.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
				);
		jPanel1.setLayout(jPanel1Layout);

		jLabel3.setText("Set Daily Insulin Dosage :");

		jLabel4.setText("Set Daily Glucagon Dosage:");

		insulinDosageField.setColumns(3);
		String insulinValue = insulinDosageField.getText().toString();

		glucagonDosageField.setColumns(3);

		populateValues();

		jLabel8.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
		jLabel8.setText(" IU ");

		jLabel10.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
		jLabel10.setText("IU ");

		saveButton.setText("Save");

		jButton3.setFont(new Font("Tahoma", Font.BOLD, 11)); // NOI18N
		jButton3.setText("Back");
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});
		jLabel9 = new javax.swing.JLabel();

		jLabel9.setFont(new java.awt.Font("Sitka Heading", 1, 18)); // NOI18N
		jLabel9.setText("Configure Patient Manual Mode :");

		chckbxManualMode.setText("Manual Mode");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		layout.setHorizontalGroup(
				layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addContainerGap()
						.addGroup(layout.createParallelGroup(Alignment.LEADING)
								.addGroup(layout.createSequentialGroup()
										.addComponent(jButton3)
										.addPreferredGap(ComponentPlacement.RELATED, 280, Short.MAX_VALUE)
										.addComponent(saveButton))
								.addGroup(layout.createSequentialGroup()
										.addGap(20)
										.addGroup(layout.createParallelGroup(Alignment.TRAILING)
												.addComponent(jLabel4)
												.addComponent(jLabel3))
										.addPreferredGap(ComponentPlacement.RELATED)
										.addGroup(layout.createParallelGroup(Alignment.LEADING)
												.addGroup(layout.createSequentialGroup()
														.addComponent(insulinDosageField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
														.addPreferredGap(ComponentPlacement.RELATED)
														.addComponent(jLabel8, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE))
												.addGroup(layout.createSequentialGroup()
														.addComponent(glucagonDosageField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
														.addPreferredGap(ComponentPlacement.UNRELATED)
														.addComponent(jLabel10)))
										.addGap(180)))
						.addContainerGap())
				.addGroup(layout.createSequentialGroup()
						.addGap(18)
						.addComponent(chckbxManualMode, GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
						.addGap(243))
				.addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE)
				.addGroup(layout.createSequentialGroup()
						.addGap(83)
						.addComponent(jLabel9)
						.addContainerGap(82, Short.MAX_VALUE))
				);
		layout.setVerticalGroup(
				layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, 37, GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(ComponentPlacement.RELATED)
						.addComponent(jLabel9)
						.addGap(19)
						.addComponent(chckbxManualMode)
						.addGap(18)
						.addGroup(layout.createParallelGroup(Alignment.BASELINE)
								.addComponent(jLabel3)
								.addComponent(insulinDosageField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel8))
						.addPreferredGap(ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
						.addGroup(layout.createParallelGroup(Alignment.BASELINE)
								.addComponent(jLabel4)
								.addComponent(glucagonDosageField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel10))
						.addGap(39)
						.addGroup(layout.createParallelGroup(Alignment.BASELINE)
								.addComponent(jButton3)
								.addComponent(saveButton))
						.addContainerGap())
				);
		getContentPane().setLayout(layout);

		pack();
	}// </editor-fold>                        

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
		// TODO add your handling code here:
	}                                        

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
		// TODO add your handling code here:
		this.setVisible(false);

		DoctorHomeView theView = new DoctorHomeView();
		theView.setVisible(true);
	}    

	public void SaveManualModeListener(java.awt.event.ActionListener listenForSaveButton) {
		saveButton.addActionListener(listenForSaveButton);
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(ConfigPatientManualView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(ConfigPatientManualView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(ConfigPatientManualView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(ConfigPatientManualView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new ConfigPatientManualView().setVisible(true);
			}
		});
	}

	protected void populateValues() {

		BufferedReader buffer = null;
		FileReader reader = null;

		try {

			reader = new FileReader(AppConstants.SET_MANUAL_MODE_FILE_PATH);
			buffer = new BufferedReader(reader);

			String line;
			while ((line = buffer.readLine()) != null) {
				if (line != null) {
					String[] split = line.split(",");
					if(split[0].equals("0"))
						chckbxManualMode.setSelected(false);
					else
						chckbxManualMode.setSelected(true);	
					insulinDosageField.setText(split[1]);
					glucagonDosageField.setText(split[2]);
				}

			}

		} catch (IOException e) {

			e.printStackTrace();

		} finally {

			try {

				if (buffer != null)
					buffer.close();

				if (reader != null)
					reader.close();

			} catch (IOException ex) {

				ex.printStackTrace();

			}

		}


	}

	// Variables declaration - do not modify                     
	private javax.swing.JButton saveButton;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JTextField jTextField2;
	private javax.swing.JTextField insulinDosageField;
	private javax.swing.JTextField glucagonDosageField;
	private javax.swing.JCheckBox chckbxManualMode;

	private int insulinValue;
	private int glucagonValue;
	// End of variables declaration   

	public javax.swing.JTextField getInsulinDosageField() {
		return insulinDosageField;
	}

	public void setInsulinDosageField(javax.swing.JTextField insulinDosageField) {
		this.insulinDosageField = insulinDosageField;
		insulinValue = Integer.parseInt(insulinDosageField.getText().toString());
	}


	public javax.swing.JTextField getGlucagonDosageField() {
		return glucagonDosageField;
	}


	public void setGlucagonDosageField(javax.swing.JTextField glucagonDosageField) {
		this.glucagonDosageField = glucagonDosageField;
		glucagonValue =  Integer.parseInt(glucagonDosageField.getText().toString());
	}


	public JCheckBox getChckbxManualMode() {
		return chckbxManualMode;
	}

	public void setChckbxManualMode(JCheckBox chckbxManualMode) {
		this.chckbxManualMode = chckbxManualMode;
	}

	public void displayErrorMessage(String errorMessage) {
		JOptionPane.showMessageDialog(this, errorMessage);
	}

	public void displaySuccessMessage(String successMessage) {
		JOptionPane.showMessageDialog(this, successMessage);
	}
}
