package com.his.scs.view;

import java.awt.Font;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;

import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.table.DefaultTableModel;

import com.his.scs.helper.AppConstants;

public class DoctorPatientHistoryView extends javax.swing.JFrame {

	/** Creates new form PatientHistoryView */
	public DoctorPatientHistoryView() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">                          
	private void initComponents() {

		jButton3 = new javax.swing.JButton();
		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jPanel2 = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();
		jButton4 = new javax.swing.JButton();

		jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		jButton3.setText("Back");
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});

		setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);

		jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, java.awt.Color.lightGray));

		jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
		jLabel1.setText("Insulin/Glucagon Pump");

		jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
		jLabel2.setText("DOCTOR MODE");
		jLabel9 = new javax.swing.JLabel();

		jLabel9.setFont(new java.awt.Font("Sitka Heading", 1, 18)); // NOI18N
		jLabel9.setText("Patient History :");

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1Layout.setHorizontalGroup(
				jPanel1Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
						.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
								.addGroup(jPanel1Layout.createSequentialGroup()
										.addGap(150)
										.addComponent(jLabel1))
								.addGroup(jPanel1Layout.createSequentialGroup()
										.addGap(239)
										.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
												.addComponent(jLabel9)
												.addComponent(jLabel2))))
						.addContainerGap(188, Short.MAX_VALUE))
				);
		jPanel1Layout.setVerticalGroup(
				jPanel1Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
						.addContainerGap()
						.addComponent(jLabel1)
						.addPreferredGap(ComponentPlacement.UNRELATED)
						.addComponent(jLabel2)
						.addPreferredGap(ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
						.addComponent(jLabel9)
						.addContainerGap())
				);
		jPanel1.setLayout(jPanel1Layout);

		createTable();
		populateTable();

		jButton4.setFont(new Font("Tahoma", Font.BOLD, 11)); // NOI18N
		jButton4.setText("Back");
		jButton4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton4ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2Layout.setHorizontalGroup(
				jPanel2Layout.createParallelGroup(Alignment.TRAILING)
				.addGroup(jPanel2Layout.createSequentialGroup()
						.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
								.addGroup(jPanel2Layout.createSequentialGroup()
										.addGap(31)
										.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 569, GroupLayout.PREFERRED_SIZE))
								.addGroup(jPanel2Layout.createSequentialGroup()
										.addContainerGap()
										.addComponent(jButton4)))
						.addContainerGap(21, Short.MAX_VALUE))
				);
		jPanel2Layout.setVerticalGroup(
				jPanel2Layout.createParallelGroup(Alignment.TRAILING)
				.addGroup(jPanel2Layout.createSequentialGroup()
						.addContainerGap()
						.addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
						.addGap(29)
						.addComponent(jButton4))
				);
		jPanel2.setLayout(jPanel2Layout);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		layout.setHorizontalGroup(
				layout.createParallelGroup(Alignment.LEADING)
				.addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
				.addGroup(layout.createSequentialGroup()
						.addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, 621, GroupLayout.PREFERRED_SIZE)
						.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
				);
		layout.setVerticalGroup(
				layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, 137, GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(ComponentPlacement.RELATED)
						.addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, 348, GroupLayout.PREFERRED_SIZE)
						.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
				);
		getContentPane().setLayout(layout);

		pack();
	}// </editor-fold>                        

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
		// TODO add your handling code here:
	}                                        

	private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {                                         
		// TODO add your handling code here:
		this.setVisible(false);

		DoctorHomeView theView = new DoctorHomeView();
		theView.setVisible(true);
	}                                        

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(DoctorPatientHistoryView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(DoctorPatientHistoryView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(DoctorPatientHistoryView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(DoctorPatientHistoryView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>


		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new DoctorPatientHistoryView().setVisible(true);
			}
		});
	}

	protected void createTable() {
		String[] columnNames = { "No", "Time", "BGL (mg/dL)", "Insulin Dose (IU)", "Glucagon Dose (IU)"};
		tableModel = new DefaultTableModel(columnNames, 0);
		/**/

		patientHistoryTable = new JTable(tableModel);
		jScrollPane1.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
		jScrollPane1.setViewportView(patientHistoryTable);
		patientHistoryTable.getColumnModel().getColumn(0).setPreferredWidth(10);
		patientHistoryTable.getColumnModel().getColumn(1).setPreferredWidth(100);
		patientHistoryTable.getColumnModel().getColumn(2).setPreferredWidth(70);
		patientHistoryTable.getColumnModel().getColumn(3).setPreferredWidth(80);
		patientHistoryTable.getColumnModel().getColumn(4).setPreferredWidth(90);
		patientHistoryTable.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
	}

	protected void populateTable() {

		BufferedReader buffer = null;
		FileReader reader = null;

		try {

			reader = new FileReader(AppConstants.PATIENT_HISTORY_FILE_PATH);
			buffer = new BufferedReader(reader);

			String line;
			int rowCount = 0;
			while ((line = buffer.readLine()) != null) {
				if (line != null) {

					String[] split = line.split(",");
					tableModel.addRow(new Object[] {Integer.toString(rowCount+1), split[0],split[1],split[2],split[3]});
					rowCount++;
				}


				//
			}

		} catch (IOException e) {

			e.printStackTrace();

		} finally {

			try {

				if (buffer != null)
					buffer.close();

				if (reader != null)
					reader.close();

			} catch (IOException ex) {

				ex.printStackTrace();

			}

		}


	}


	// Variables declaration - do not modify                     
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton4;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable jTable1;
	private javax.swing.JTable patientHistoryTable;
	private DefaultTableModel tableModel;
	// End of variables declaration                   

}