package com.his.scs.view;

import java.awt.Component;
import java.awt.SystemColor;

import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.SwingConstants;

import com.his.scs.controller.ConfigPatientManualController;
import com.his.scs.controller.DoctorPatientHistoryController;
import com.his.scs.controller.PatientDetailsController;
import com.his.scs.model.ConfigPatientManualModel;
import com.his.scs.model.DoctorPatientHistoryModel;
import com.his.scs.model.PatientDetailsModel;

public class DoctorHomeView extends javax.swing.JFrame {

	/**
	 * Creates new form DoctorHomeView
	 */
	public DoctorHomeView() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">                          
	private void initComponents() {

		jScrollPane1 = new javax.swing.JScrollPane();
		jTextPane1 = new javax.swing.JTextPane();
		jMenu1 = new javax.swing.JMenu();
		jMenu2 = new javax.swing.JMenu();
		jMenu3 = new javax.swing.JMenu();
		jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jPanel2 = new javax.swing.JPanel();
		btnEditDetails = new javax.swing.JButton();
		btnEditDetails.setBackground(SystemColor.inactiveCaption);
		btnConfigMode = new javax.swing.JButton();
		btnConfigMode.setBackground(SystemColor.inactiveCaption);
		btnViewHistory = new javax.swing.JButton();
		btnViewHistory.setBackground(SystemColor.inactiveCaption);
		btnBack = new javax.swing.JButton();

		jScrollPane1.setViewportView(jTextPane1);

		jMenu1.setText("jMenu1");

		jMenu2.setText("jMenu2");

		jMenu3.setText("jMenu3");

		jCheckBoxMenuItem1.setSelected(true);
		jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

		setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);

		jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, java.awt.Color.lightGray));

		jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
		jLabel1.setText("Insulin/Glucagon Pump");

		jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
		jLabel2.setText("DOCTOR MODE");

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1Layout.setHorizontalGroup(
				jPanel1Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
						.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
								.addGroup(jPanel1Layout.createSequentialGroup()
										.addGap(109)
										.addComponent(jLabel1))
								.addGroup(jPanel1Layout.createSequentialGroup()
										.addGap(185)
										.addComponent(jLabel2)))
						.addContainerGap(124, Short.MAX_VALUE))
				);
		jPanel1Layout.setVerticalGroup(
				jPanel1Layout.createParallelGroup(Alignment.TRAILING)
				.addGroup(Alignment.LEADING, jPanel1Layout.createSequentialGroup()
						.addGap(26)
						.addComponent(jLabel1)
						.addGap(18)
						.addComponent(jLabel2)
						.addContainerGap(21, Short.MAX_VALUE))
				);
		jPanel1.setLayout(jPanel1Layout);

		btnEditDetails.setText("Edit Patient Details");
		btnEditDetails.setSelected(false);
		btnEditDetails.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		btnConfigMode.setText("Configure Patient Manual Mode");
		btnConfigMode.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});

		btnViewHistory.setText("View Patient History");
		btnViewHistory.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton4ActionPerformed(evt);
			}
		});

		btnBack.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
		btnBack.setText("Back to Home Screen");
		btnBack.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2Layout.setHorizontalGroup(
				jPanel2Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup()
						.addContainerGap(355, Short.MAX_VALUE)
						.addComponent(btnBack)
						.addContainerGap())
				.addGroup(jPanel2Layout.createSequentialGroup()
						.addGap(160)
						.addGroup(jPanel2Layout.createParallelGroup(Alignment.TRAILING)
								.addComponent(btnViewHistory)
								.addComponent(btnConfigMode)
								.addComponent(btnEditDetails))
						.addContainerGap(181, Short.MAX_VALUE))
				);
		jPanel2Layout.setVerticalGroup(
				jPanel2Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup()
						.addGap(19)
						.addComponent(btnEditDetails, GroupLayout.PREFERRED_SIZE, 38, GroupLayout.PREFERRED_SIZE)
						.addGap(36)
						.addComponent(btnConfigMode, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
						.addGap(41)
						.addComponent(btnViewHistory, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
						.addComponent(btnBack)
						.addContainerGap())
				);
		jPanel2Layout.linkSize(SwingConstants.HORIZONTAL, new Component[] {btnEditDetails, btnConfigMode, btnViewHistory});
		jPanel2.setLayout(jPanel2Layout);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		layout.setHorizontalGroup(
				layout.createParallelGroup(Alignment.LEADING)
				.addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				.addComponent(jPanel2, GroupLayout.DEFAULT_SIZE, 526, Short.MAX_VALUE)
				);
		layout.setVerticalGroup(
				layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, 294, GroupLayout.PREFERRED_SIZE))
				);
		getContentPane().setLayout(layout);

		pack();
	}// </editor-fold>                        

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
		// TODO add your handling code here:
		this.setVisible(false);

		ConfigPatientManualView theView = new ConfigPatientManualView();
		ConfigPatientManualModel theModel = new ConfigPatientManualModel();

		ConfigPatientManualController theController = new ConfigPatientManualController(theView, theModel);
		theView.setVisible(true);
	} 

	private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {                                         
		// TODO add your handling code here:
		this.setVisible(false);

		DoctorPatientHistoryView theView = new DoctorPatientHistoryView();
		DoctorPatientHistoryModel theModel = new DoctorPatientHistoryModel();

		DoctorPatientHistoryController theController = new DoctorPatientHistoryController(theView, theModel);
		theView.setVisible(true);
	}  

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
		// TODO add your handling code here:
		this.setVisible(false);

		PatientDetailsView theView = new PatientDetailsView();
		PatientDetailsModel theModel = new PatientDetailsModel();

		PatientDetailsController theController = new PatientDetailsController(theView, theModel);
		theView.setVisible(true);
	}                                        

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
		// TODO add your handling code here:
		this.dispose();

		HomeFrame theView = new HomeFrame();
		theView.setVisible(true);
	}  


	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(DoctorHomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(DoctorHomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(DoctorHomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(DoctorHomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new DoctorHomeView().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify                     
	private javax.swing.JButton btnBack;
	private javax.swing.JButton btnEditDetails;
	private javax.swing.JButton btnConfigMode;
	private javax.swing.JButton btnViewHistory;
	private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JMenu jMenu1;
	private javax.swing.JMenu jMenu2;
	private javax.swing.JMenu jMenu3;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTextPane jTextPane1;
	// End of variables declaration                   
}

